appVolumeMounts:
  config:
    emptyDir: true
    mountPath: /config
clashCoreServerHttp:
  port: 9090
emptyDirVolumes: true
environmentVariables: []
extraAppVolumeMounts:
- hostPath: /mnt/extras/something
  mountPath: /mnt/extras
  readOnly: true
gpuConfiguration: {}
hostNetwork: false
image:
  pullPolicy: IfNotPresent
  repository: dreamacro/clash
  tag: latest
updateStrategy: Recreate
