apiVersion: v2
appVersion: 1.0.0
dependencies:
- name: common
  repository: file://../../../library/common/2207.0.0
  version: 2207.0.0
description: 筛选自己需要的应用,重新生成catalog
home: https://github.com/tuky/StripCharts 
icon: https://gitee.com/qwerty0007/xchart/raw/main/assets/stripcharts.jpg
keywords:
- media
name: stripcharts
version: 1.0.1
