image:
  repository: cnk3x/xunlei
  pullPolicy: IfNotPresent
  tag: latest

securityContext:
  readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        port: 22345
        targetPort: 2345

persistence:
  config:
    enabled: true
    mountPath: "/xunlei/data"
  downloads:
    enabled: true
    mountPath: "/xunlei/downloads"


portal:
  enabled: true
