image:
  repository: dh.tccr.io/truecharts/alist
  pullPolicy: IfNotPresent
  tag: 2.6.4@sha256:a268951c7e96d20f3176650ff974b08db16b9d62fe2c6433d4496a7ece753959

service:
  main:
    ports:
      main:
        targetPort: 8063
        port: 18063

persistence:
  data:
    enabled: true
    mountPath: "/config"
  upload:
    enabled: true
    mountPath: "/upload"

portal:
  enabled: true
