image:
  repository: mtphotos/mt-photos
  pullPolicy: IfNotPresent
  tag: latest@sha256:10d187608cb0a7af1102e435c4a864c75bbf1c09895059bd8af0ab5c2175b025

service:
  main:
    ports:
      main:
        targetPort: 8063
        port: 18063

persistence:
  data:
    enabled: true
    mountPath: "/config"
  upload:
    enabled: true
    mountPath: "/upload"

portal:
  enabled: true
